## Import libraries

In [12]:
import pandas as pd
import numpy as np

## Load the cleaned dataset

In [8]:
df = pd.read_csv("~/Downloads/Superstore_dataset.csv")

## Check Dataset

In [14]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015

## Convert date columns

In [9]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

## Create Year

In [10]:
df["Year"] = df["Order Date"].dt.year

In [11]:
df[["Order Date","Year"]].head()

  Order Date  Year
0 2016-11-08  2016
1 2016-11-08  2016
2 2016-06-12  2016
3 2015-10-11  2015
4 2015-10-11  2015

## Create Month

In [15]:
df["Month"] = df["Order Date"].dt.month_name()

In [16]:
df[["Order Date", "Month"]].head()

  Order Date     Month
0 2016-11-08  November
1 2016-11-08  November
2 2016-06-12      June
3 2015-10-11   October
4 2015-10-11   October

## Create Quarter

In [17]:
df["Quarter"] = df["Order Date"].dt.quarter

In [18]:
df[["Order Date", "Quarter"]].head()

  Order Date  Quarter
0 2016-11-08        4
1 2016-11-08        4
2 2016-06-12        2
3 2015-10-11        4
4 2015-10-11        4

## Create Shipping Days

In [19]:
df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

In [20]:
df[["Order Date", "Ship Date", "Shipping Days"]].head()

  Order Date  Ship Date  Shipping Days
0 2016-11-08 2016-11-11              3
1 2016-11-08 2016-11-11              3
2 2016-06-12 2016-06-16              4
3 2015-10-11 2015-10-18              7
4 2015-10-11 2015-10-18              7

## Create Profit Margin

In [21]:
df["Profit Margin"] = (df["Profit"] / df["Sales"]) * 100

In [22]:
df[["Sales", "Profit", "Profit Margin"]].head()

      Sales    Profit  Profit Margin
0  261.9600   41.9136          16.00
1  731.9400  219.5820          30.00
2   14.6200    6.8714          47.00
3  957.5775 -383.0310         -40.00
4   22.3680    2.5164          11.25

## Create Average Selling Price

In [23]:
df["Average Selling Price"] = df["Sales"] / df["Quantity"]

In [24]:
df[["Sales", "Quantity", "Average Selling Price"]].head()

      Sales  Quantity  Average Selling Price
0  261.9600         2               130.9800
1  731.9400         3               243.9800
2   14.6200         2                 7.3100
3  957.5775         5               191.5155
4   22.3680         2                11.1840

## Create Discount Category

In [25]:
df["Discount Category"] = pd.cut(
    df["Discount"],
    bins=[-0.01, 0, 0.2, 0.5, 1],
    labels=["No Discount", "Low", "Medium", "High"]
)

In [26]:
df[["Discount", "Discount Category"]].head()

   Discount Discount Category
0      0.00       No Discount
1      0.00       No Discount
2      0.00       No Discount
3      0.45            Medium
4      0.20               Low

## Create Sales Category

In [27]:
df["Sales Category"] = pd.cut(
    df["Sales"],
    bins=[0, 100, 500, 1000, 25000],
    labels=["Low", "Medium", "High", "Very High"]
)

In [28]:
df[["Sales", "Sales Category"]].head()

      Sales Sales Category
0  261.9600         Medium
1  731.9400           High
2   14.6200            Low
3  957.5775           High
4   22.3680            Low

## Create Order Size

In [29]:
df["Order Size"] = pd.cut(
    df["Quantity"],
    bins=[0, 2, 5, 14],
    labels=["Small", "Medium", "Large"]
)

In [30]:
df[["Quantity", "Order Size"]].head()

   Quantity Order Size
0         2      Small
1         3     Medium
2         2      Small
3         5     Medium
4         2      Small

## Verify All New Columns

In [31]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Profit,Year,Month,Quarter,Shipping Days,Profit Margin,Average Selling Price,Discount Category,Sales Category,Order Size
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,41.9136,2016,November,4,3,16.00,130.9800,No Discount,Medium,Small
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,219.5820,2016,November,4,3,30.00,243.9800,No Discount,High,Medium
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,6.8714,2016,June,2,4,47.00,7.3100,No Discount,Low,Small
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,-383.0310,2015,October,4,7,-40.00,191.5155,Medium,High,Medium
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,2.5164,2015,October,4,7,11.25,11.1840,Low,Low,Small

## Save the Feature-Engineered Dataset

In [32]:
df.to_csv("feature_engineered_superstore.csv", index=False)